version: '3.8'

services:
  traefik:
    image: traefik:latest
    environment:
      - TRAEFIK_CERTIFICATERESOLVERS_LETSENCRPTY_ACME_EMAIL=${ACME_EMAIL}
      - TRAEFIK_CERTIFICATESRESOLVERS_BUYPASS_ACME_EMAIL=${ACME_EMAIL}
    container_name: traefik
    restart: always
    security_opt:
      - no-new-privileges:true
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/traefik.yml:/traefik.yml:ro
      - ./data/acme-le.json:/acme-le.json
      - ./data/acme-buypass.json:/acme-buypass.json
      # Ensure dynamic.yml is inside this folder on your host
      - ./data/configurations:/configurations:ro
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.traefik-secure.entrypoints=websecure"
      # Replace with your actual domain
      - "traefik.http.routers.traefik-secure.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.traefik-secure.middlewares=user-auth@file"
      - "traefik.http.routers.traefik-secure.service=api@internal"
      # v3 requires TLS to be explicitly enabled on the router if not global
      - "traefik.http.routers.traefik-secure.tls.certresolver=letsencrypt"

networks:
  proxy:
    external: true